version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "19:00"
      timezone: "Europe/Paris"
    assignees:
      - "wyzedix"
    target-branch: "dev"
