name: CI

on: [push]

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - name: Checking out the repo
              uses: actions/checkout@v3

            - name: Setup node 18
              uses: actions/setup-node@v3
              with:
                  node-version: "18"
                  cache: "npm"

            - name: Installing dependencies
              run: npm ci

            - name: Checking format
              run: npm run ci:format-check

            - name: Checking linter
              run: npm run ci:linter-check

            - name: Checking typescript
              run: npm run ci:ts-check
